---
title: "05_Evaluation"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir= normalizePath('..'))
```

# Evaluation

The analysis performed for the business goal yielded results on system performance and findings. These results are described and evaluated below.

## Dominated Event Type

**Render** event accounts for **94.5%** of the time it takes to generate a terapixel image. Uploading 3.19 percent, Tilling 2.23 percent, and Saving config activities 000.5 percent account for the rest. Render activity, which takes an average of **41.2** seconds, dominates the whole process.

## Performance impact on Gpu metrics

Since there was no data on the quality of the tile created, the performance was determined as the time it took to create a tile.

- **Temperature:** After examining the relationship between GPU temperature and performance, it was determined that the standard deviation of temperature had a minor impact on performance.

- **Power Draw:**  There is some positive correlation between the median, standard deviation and maximum value of power draw and performance.


## Variation in computation requirements for particular tiles?

The terapixel image's **visual legend** in the top left corner was rendered in a short amount of time and with less power. The rendering time of uncomplicated or monochrome structures and places is also very low, and also there is difference between the computations required to render streets and buildings. In addition, at the beginning of the process, that is, at the left starting points of the the  terapixel image, the system does not work efficiently. It takes too much time to render.

## GPU cards with different performance

A total of 12 GPU card models were discovered with our approach. The GPU card with the best performance is the one whose serial number starts with **4203** with an average rendering time of 41.6 seconds. On the other hand, the performance of GPU cards starting with **3241** and **3243** is lower than the others. Since there are 65,793 operations in total, the improvement to be made here is critical.

## Efficiency of the task scheduling

We calculated the efficiency of task scheduling based on how much delay there was in scheduling for each machine.
As a result, the delay time of machines in the task scheduling process ranges from **125.5 seconds** to **178.8 seconds**. The average time lost is **151.1 seconds**. In other words, each of the 1024 machines in the cloud system does not do a job for an average of 2.5 minutes. The improvement to be made here will increase the performance of the system.
